### ISSUE TITLE
Multi Layout File with different length of records

### ISSUE THREAD

**Issue by pargass31** [aws-samples/mainframe-data-utilities#12]
Hi,
First, thank a lot for this package and the huge work, it's really helpful!

**I have a multi layout file and the total length of a record is not always the same.**

I tried to simplified my example, the transformation rules are like:

          "transf1": [
                    {
                              "type": "ch",
                              "bytes": 2,
                              "offset": 0,
                              "dplaces": 0,
                              "name": "FIELD_1",
                              "part-key": false,
                              "sort-key": false
                    },
                    .....
                    {
                              "type": "ch",
                              "bytes": 10,
                              "offset": 500,
                              "dplaces": 0,
                              "name": "FIELD_2",
                              "part-key": false,
                              "sort-key": false
                    }],
          "transf2": [
                    {
                              "type": "ch",
                              "bytes": 2,
                              "offset": 0,
                              "dplaces": 0,
                              "name": "FIELD_1",
                              "part-key": false,
                              "sort-key": false
                    },
                    .....
                    {
                              "type": "ch",
                              "bytes": 50,
                              "offset": 500,
                              "dplaces": 0,
                              "name": "FIELD_2",
                              "part-key": false,
                              "sort-key": false
                    }]

**-> The bytes for the last field can be 10 or 50*
**-> The total bytes for one record can be 510 or 550.**

-> I can see if I have to use transf1 or transf2 by looking at a specific offset so:

          "transf_rule": [
		                      {
                              "offset": 138,
                              "size": 3,
                              "hex": "404040",
                              "transf": "transf1"
                    },
                    {
                              "offset": 138,
                              "size": 3,
                              "hex": "E2C4F0",
                              "transf": "transf2"
                    }

-> But the issue is that when a record is read, the input_recl parameter used to determine the length is fix and the transf to used is determined after.
-> Do I miss something?

**Comment by luisdant** [comment]
Hello pargass31!

Thank you for your message.

If your multi layout file is also "multi record length" file you've got a Variable Length Blocked (VB) file (https://www.ibm.com/docs/es/epfz/5.3?topic=formats-variable-length-records).

I see 2 alternatives:

1. FTP your file keeping the RDW (first 4 bytes) (https://bit.listserv.ibm-main.narkive.com/a5Jp3eHb/rdw-with-ftp) and parse it as a VB file (https://github.com/aws-samples/mainframe-data-utilities/blob/main/docs/04-local-single-vb.md)

2. Convert your file from VB to FB on the mainframe before transferring it out and use the same feature as you are using now.

Please, let me know if that works for you.

thx!

**Comment by pargass31** [comment]
Thanks for you answer.
I extract the file using retrbinary method (sess.retrbinary('RETR %s' % mainframe_file, open(local_file_ebcdic_path, 'wb').write)).
It appears that the RDW is not extracting with this method, because if I specified "input_recfm": "vb" in the json because in the 
read function, l = getRDW(input.read(4)) return something not corresponding to the length of the record (but the length of the full file I think).

Do you know how to specify that I want a the RDW in the sess.retrbinary?

**Comment by luisdant** [comment]
I suppose you are using [ftplib](https://docs.python.org/3/library/ftplib.html#module-ftplib). Right?

A binary transfer is not enough. You need to tell the server that you want the RDW.

I've never used `ftplib` by I'd try something like this **before** `retrbinary`:
```
sess.sendcmd('quote site rdw')
```

**Comment by pargass31** [comment]
yes I'm ussing ftplib, this command is not working but I'm checking from another one

**Comment by luisdant** [comment]
To check if your file contains the RDW investigate using hexadecimal:
```
head -c 10 your/ebcdic/file | xxd
```

**Comment by pargass31** [comment]
i'm using Hxd to see the file, I should see the RDW if extracted?
![image](https://github.com/aws-samples/mainframe-data-utilities/assets/58304005/823846c9-9f7b-47ee-91ba-c631af0a4f97)

**Comment by luisdant** [comment]
Yes, the RDW must figure in the beginning of each record. I recommend you manually FTP the file first to isolate the issue and understand the data.

**Comment by pargass31** [comment]
You mean with filezila or equivalent? I'm not able to see any file with a simple filezila connection

**Comment by pargass31** [comment]
In fact I just need to sess.sendcmd("site rdw") and I have the rdw extracted.
Thanks!

**Comment by pargass31** [comment]
It's working fine, thanks a lot for the help.

**Comment by pargass31** [comment]
it's working fine, thanks a lot again
