### ISSUE TITLE
*list.json failing to convert EBCDIC file correctly

### ISSUE THREAD

**Issue by cjbstpaul** [aws-samples/mainframe-data-utilities#2]
. Currently, we have a file that we cannot successfully convert using the json that is generated from the copy book we have been provided and request that your team review.

The attached zip file contains the following. The notes included are the known information based on our understanding of how the process works to create a json file that is used to determine how to convert the file from EBCDIC to ASCII.

1)	The original copy book  

2)	The *-list.json which contains the transformation parameters that tell the python script how to read the EBCDIC file.
* Note that it is a multi-layout copy book with 3 record types (meaning 2 redefines). Of these two redefines only one is required. The data file we are processing only contains 2 of the three record types. As noted in the copy book the record type values are 10 and 20, respectively. 10 represents personal information and 20 represents check information. There is not a record in the data file for police information (which would have been record type 30). However, it is included in the copy book. The trans-rule has been added for the check redefine (record type 20). Based on my understanding of the README.md file provided a trans-rule would not be needed for personal information since it is not a redefine (record type 10). In the file the relevant transformations for the different records types are transf (personal) ,transf1 (check), and transf2 (police). There is a transf3 that seems to be related to the in-record redefine discussed in the next section.

** Additionally, there is an ‘in-record’ redefine in the check information record to redefine the format of a field on the check record). It seems that when the copy book is processed, it is creating a forth transformation to handle this. However, the other fields included in the redefine are all related to the police record and not the check record.

3)	The *-dict.json file which is a data dictionary.

Thanks,
[DIFSDB.zip](https://github.com/aws-samples/mainframe-data-utilities/files/8421002/DIFSDB.zip)

Craig
CRAIG BAUMGARTNER

**Comment by luisdant** [comment]
Hi Craig,

I'm glad that you are running this sample, and therefore helping to improve it.

By the json you've provided It seems that the field you are considering for the transformation rule is `DB-RECORD-TYPE`. Is that correct?

```
003400             15  DB-RECORD-TYPE            PIC XX.                00000053
003500                 88  DB-PERSONAL-RECORD    VALUE '10'.            00000054
003600                 88  DB-OFFENSE-RECORD     VALUE '20'.            00000055
```

DB-RECORD-TYPE is a character element (PIC XX), which means that its '20' hexadecimal representation is '0200' and not '0014'. 

Please run again with the configuration below and attach a sample of the input file (without PII) if the undesired behaviour persists.

```
"transf-rule": [
	{	
	"offset": 29,
	"size": 2,
	"hex": "0200",
	"transf": "transf1"
	}
    ]
```

**Comment by cjbstpaul** [comment]
Luis,

I replaced the hex value as you suggested and the problem persists. I have spoken with my client and they will have to get a file with dummy data.

As an aside, the value I used was the decimal value of 20 instead of the character value which I now understand is incorrect. However, when I enter the character value 20 in any of the online converter it converts to 3230. I do not understand how the hex value of 0200 is derived from the ASCII value of 20. Is there a converter that you are using that is available to me?

Thanks,

Craig

CRAIG BAUMGARTNER
Prinicpal Consultant

CAPCO | 2550 Pacific Avenue, Suite 700 | Dallas, Texas 75226
W: www.capco.com<http://www.capco.com/>
M: 319.431.7732

***@***.***<https://www.twitter.com/capco>     <https://www.facebook.com/capcoglobal>       ***@***.*** <https://www.youtube.com/capco_global>      ***@***.*** <https://www.linkedin.com/company/capco>      ***@***.*** <https://www.instagram.com/capco_global/>
***@***.***



***@***.***  Please consider the environment before printing this email

**Comment by luisdant** [comment]
I'm sorry, Craig. I was distracted.

"F2F0" is the right hex value. Please check the decimal 240 and 242 values in the table below. 

https://www.ibm.com/docs/en/xl-fortran-linux/15.1.0?topic=appendix-ascii-ebcdic-character-sets

"3230" is the hexadecimal representation of "20" when the data is encoded in ASCII.

Regards,

Luis

**Comment by cjbstpaul** [comment]
Luis,

I have tried using F2F0 and the problem persists.

Currently, I am working with my team to get a dummy file so that you can test it on your side.

Thanks,

Craig

CRAIG BAUMGARTNER
Prinicpal Consultant

CAPCO | 2550 Pacific Avenue, Suite 700 | Dallas, Texas 75226
W: www.capco.com<http://www.capco.com/>
M: 319.431.7732

***@***.***<https://www.twitter.com/capco>     <https://www.facebook.com/capcoglobal>       ***@***.*** <https://www.youtube.com/capco_global>      ***@***.*** <https://www.linkedin.com/company/capco>      ***@***.*** <https://www.instagram.com/capco_global/>
***@***.***



***@***.***  Please consider the environment before printing this email

**Comment by luisdant** [comment]
Ok, Craig. Please, send me the file when you have it.

**Comment by cjbstpaul** [comment]
Hi Luis,

Attached is the masked data file you can use for validating this issue.   Apologies for the delay.
Craig will be back in the office tomorrow if you have follow-up questions/

Thanks,
Emily


Emily Tidwell
CAPCO
M: 713 794 6745

From: Baumgartner, Craig ***@***.***>
Sent: Wednesday, April 6, 2022 10:42 AM
To: aws-samples/mainframe-data-utilities ***@***.***>; aws-samples/mainframe-data-utilities ***@***.***>
Cc: Author ***@***.***>; Veetil, Anil ***@***.***>; Tidwell, Emily ***@***.***>; Sumit Khadka ***@***.***>; Udrick Azinue ***@***.***>
Subject: RE: [aws-samples/mainframe-data-utilities] *list.json failing to convert EBCDIC file correctly (Issue #2)

Luis,

I have tried using F2F0 and the problem persists.

Currently, I am working with my team to get a dummy file so that you can test it on your side.

Thanks,

Craig

CRAIG BAUMGARTNER
Prinicpal Consultant

CAPCO | 2550 Pacific Avenue, Suite 700 | Dallas, Texas 75226
W: www.capco.com<http://www.capco.com/>
M: 319.431.7732

***@***.***<https://www.twitter.com/capco>     <https://www.facebook.com/capcoglobal>       ***@***.*** <https://www.youtube.com/capco_global>      ***@***.*** <https://www.linkedin.com/company/capco>      ***@***.*** <https://www.instagram.com/capco_global/>
***@***.***



***@***.***  Please consider the environment before printing this email

**Comment by luisdant** [comment]
> 

Hello, Emily. I cannot see the file.
