### ISSUE TITLE
EBCDIC to ASCII conversion on column level redefine fails on json conversion

### ISSUE THREAD

**Issue by anilcert** [aws-samples/mainframe-data-utilities#3]
When there is a column level redefine in the copybook the ascii conversion is not able to parse the file properly.
[DIFSDB.zip](https://github.com/aws-samples/mainframe-data-utilities/files/8516100/DIFSDB.zip)

**Comment by luisdant** [comment]
Hi. It seems there is a gap in the copybook parser.

I've created this rule:

    "transf-rule": [
        {
            "offset": 29,
            "size": 2,
            "hex": "f2f0",
            "transf": "transf1"
        }

And changed the following "transf1" node:
```
        {
            "type": "zd+",
            "bytes": 7,
            "offset": 133,
            "dplaces": 2,
            "name": "DB-CK-AMT",
            "part-key": false,
            "sort-key": false
        },
```

Attached is the changed meta data file:

/Users/luisdant/Downloads/DIFSDB (1)/mainframe-data-utilities/DIFSDB-list.json

PS, I still need to check the DB-CK-SEVERITY-CODE.

**Comment by anilcert** [comment]
Thank you so much Luis.We will try to parse the file after changing the json file.

**Comment by luisdant** [comment]
It seems that there are actually 2 decimal fields within DB-CK-SEVERITY-CODE.

![Screen Shot 2022-04-20 at 08 10 59](https://user-images.githubusercontent.com/88108595/164218379-eeedbd04-7663-4921-a3a7-1365ec3be3d6.png)

I've split into 2 fields and the result file looks good.

![Screen Shot 2022-04-20 at 08 13 39](https://user-images.githubusercontent.com/88108595/164218921-162f7a8e-7235-4243-b9e2-465c35f2a880.png)

![Screen Shot 2022-04-20 at 08 16 41](https://user-images.githubusercontent.com/88108595/164219169-879512e8-fbdd-4a50-9cb5-6392137289b7.png)

This weekend I'll make a quick change in the code to consider the "upper case" and "lower case" hexadecimal values in the transformation rule (e.g. F2F0 and f2f0), and I'll document the REDEFINES gap on readme file.

Please, let me know if the workaround is ok for now and I'll close the issue.

**Comment by anilcert** [comment]
Updated the copybook to split the DB-CHK-SEVERITY-CODE into 2 fields.
Edited the json file with transformation rule added and 'transf1' for DB-CHK-AMT.
But the output is not matching with the one you got.I am attaching files for your reference.

**Comment by anilcert** [comment]
[Masked.zip](https://github.com/aws-samples/mainframe-data-utilities/files/8524243/Masked.zip)

**Comment by luisdant** [comment]
Hi Anil,

I'm sorry. I forgot to mention. I've found the same problem, and it worked well when I changed the DB-CHECK-RMKS1 from PIC X(30) to PIC X(29). Would it be bad data?

Attached are the changed copybook and the corresponding json.

[difsdb3.zip](https://github.com/aws-samples/mainframe-data-utilities/files/8524773/difsdb3.zip)

Best Regards
Luis

**Comment by anilcert** [comment]
We analysed the output ASCII and have questions to the client as the copy book has a mismatch with the data in  "DB-CHK-SEVERITY-CODE" and waiting for the response.

**Comment by luisdant** [comment]
Anil,

As suspected I found an issue in the data item length calculation, which was happening with packed-decimals having 3 figures or less.

The version available now has processed the DFISMAST file. I just had to manually change that unsupported redefines data item.

Attached are the copybook, json list and result ASCII file. Can you please review?

[DIFSMAST.zip](https://github.com/aws-samples/mainframe-data-utilities/files/8596716/DIFSMAST.zip)

**Comment by anilcert** [comment]
We are able to  convert the packed decimal values properly now after the fix.

Thank you
