### ISSUE TITLE
AWS Mainframe Data Utility Capabilities

### ISSUE THREAD

**Issue by cjbstpaul** [aws-samples/mainframe-data-utilities#4]
Does the utility as currently built support the following copy book features:

1) Occurs
2) Variable length records

Thanks in advance,

Craig

**Comment by luisdant** [comment]
HI Craig.

Yes, it supports occurs. 

Do you mean [Variable Blocked (VB)](https://www.ibm.com/docs/en/zos-basic-skills?topic=set-data-record-formats) record format? 

No, it doesn't support VB files currently, but this format can be easily converted from to FB in the source environment. Please refer to https://www.ibm.com/docs/en/zos/2.3.0?topic=reports-converting-fb-vb

Thx!

Luis
