### ISSUE TITLE
Future Functionality

### ISSUE THREAD

**Issue by cjbstpaul** [aws-samples/mainframe-data-utilities#5]
Currently, the utility does not generate logs application activities, including records read and records written. Will this be added in the future and if so what is the timeline.

Thansk,

Craig

**Comment by luisdant** [comment]
Hi Craig. 

It shows the number of converted records when the script finishes. 

`------------------------------------------------------------------`
`2022-04-26 13:23:20.473380 | Local Json file   | -local-json | DIFSDB3-list.json`
`2022-04-26 13:23:21.223569 | Records processed | 5000`
`2022-04-26 13:23:21.223632 Seconds 0.750293`

Additionally if you want intermediate status, you can set its frequency by changing the "print" parameter in the JSON metadata file.

`"print": 1000 `

`------------------------------------------------------------------`
`2022-04-26 13:28:36.462468 | Local Json file   | -local-json | DIFSDB3-list.json`
`2022-04-26 13:28:36.608398 | Records processed | 1000`
`2022-04-26 13:28:36.768393 | Records processed | 2000`
`2022-04-26 13:28:36.882876 | Records processed | 3000`
`2022-04-26 13:28:36.999609 | Records processed | 4000`
`2022-04-26 13:28:37.115104 | Records processed | 5000`
`2022-04-26 13:28:37.115249 | Records processed | 5000`
`2022-04-26 13:28:37.115295 Seconds 0.653043`

Is there anything else that you would like to see?

Thx

Luis

**Comment by cjbstpaul** [comment]
It would be beneficial if the information was written to a log file instead of as screen output. We will be calling your module many times from another script and it will not be monitored by a user. Is this possible?

Regarding the number of records your output indicates the number of records written but not the number of records read. An incorrect copy book does not guarantee failure of the process so we want to be able to balance the number of records read into the process versus the number that is output. Is it possible to capture both?
________________________________

**Comment by luisdant** [comment]
As regards the log file. Where do you think it should be written?  Have you tried to search them on CloudWatch?

**Comment by cjbstpaul** [comment]
Luis,

With regard to a log file, we can just redirect the screen output to a file that we will parse for information instead of asking for an enhancement.

Regarding writing the number of records read from the EBCDIC file (in addition to the number written to the ASCII output file), is adding that an option?

Thanks,

Craig

CRAIG BAUMGARTNER
Prinicpal Consultant

CAPCO | 2550 Pacific Avenue, Suite 700 | Dallas, Texas 75226
W: www.capco.com<http://www.capco.com/>
M: 319.431.7732

***@***.***<https://www.twitter.com/capco>     <https://www.facebook.com/capcoglobal>       ***@***.*** <https://www.youtube.com/capco_global>      ***@***.*** <https://www.linkedin.com/company/capco>      ***@***.*** <https://www.instagram.com/capco_global/>
***@***.***



***@***.***  Please consider the environment before printing this email

**Comment by luisdant** [comment]
Hi Craig,

Yes, adding different read/write count can be an option. Do you have any evidence of differences between these numbers?

**Comment by cjbstpaul** [comment]
Luis,

I do not have evidence of it when a the  .json is configured correctly, but have experienced it when I did not configure the trans_rule correctly.

Thanks,

Craig

CRAIG BAUMGARTNER
Prinicpal Consultant

CAPCO | 2550 Pacific Avenue, Suite 700 | Dallas, Texas 75226
W: www.capco.com<http://www.capco.com/>
M: 319.431.7732

***@***.***<https://www.twitter.com/capco>     <https://www.facebook.com/capcoglobal>       ***@***.*** <https://www.youtube.com/capco_global>      ***@***.*** <https://www.linkedin.com/company/capco>      ***@***.*** <https://www.instagram.com/capco_global/>
***@***.***



***@***.***  Please consider the environment before printing this email

**Comment by luisdant** [comment]
I'd like to see what happens, Craig.

It looks like a bug. doesn't it?

**Comment by cjbstpaul** [comment]
Give me your day after and I will see if I can reproduce it.
________________________________

**Comment by luisdant** [comment]
Hi. Can I close this issue?
