### ISSUE TITLE
Verify Format of the File

### ISSUE THREAD

**Issue by cjbstpaul** [aws-samples/mainframe-data-utilities#6]
Does the MDU perform any validation to confirm that the file type is binary?

**Comment by luisdant** [comment]
Can I close this one? Do you have a suggestion about how to validate?

**Comment by cjbstpaul** [comment]
You can close the ticket… I don’t have a suggestion. The answer may be to add the information to a metadata file when transferred from the mainframe.

Thanks,

Craig
CRAIG BAUMGARTNER
Prinicpal Consultant

CAPCO | 2550 Pacific Avenue, Suite 700 | Dallas, Texas 75226
W: www.capco.com<http://www.capco.com/>
M: 319.431.7732

***@***.***<https://www.twitter.com/capco>     <https://www.facebook.com/capcoglobal>       ***@***.*** <https://www.youtube.com/capco_global>      ***@***.*** <https://www.linkedin.com/company/capco>      ***@***.*** <https://www.instagram.com/capco_global/>
***@***.***



***@***.***  Please consider the environment before printing this email

**Comment by luisdant** [comment]
Thanks, Craig.
