### ISSUE TITLE
Copy Book reading issue.

### ISSUE THREAD

**Issue by anilcert** [aws-samples/mainframe-data-utilities#7]
We are getting an error while running the copybook to json python script.Attached the copybook and error files.Please take a look
thank you
[Error.txt](https://github.com/aws-samples/mainframe-data-utilities/files/8578129/Error.txt)
[syndisp.zip](https://github.com/aws-samples/mainframe-data-utilities/files/8578131/syndisp.zip)

**Comment by luisdant** [comment]
Hi Anil,

It seems to be [VB file](https://www.ibm.com/docs/en/zos-basic-skills?topic=set-data-record-formats), which is not supported. But anyways I'll fix this weird parsing error.

**Comment by luisdant** [comment]
Hi Anil,

I found that the error happens because the copybook is shifted to the left (it's starting on column 1 and it should be starting at 7) and there is also a blank line within it. I'll create a fix to validate this and make it clearer.

Anyways, OCCURS DEPENDING ON and VB aren't supported yet. I'm also documenting this on readme to make it clearer.

Regards

**Comment by anilcert** [comment]
Are you planning to add the OCCURS DEPENDING ON < column> in the utility soon?  Please let me know.

**Comment by luisdant** [comment]
I've changed the current version (pushed to git yesterday) and the copybook above (SYNDISP) is already being interpreted.

Let me know if you have data that could be used to test the encoding conversion.

**Comment by anilcert** [comment]
Thank you Luis.
Is this version take care of files having OCCURS DEPENDING ON <column> in it ?
I have a very big file to test, in my server and we already requested a small sample masked file to TEST with, and waiting.

**Comment by anilcert** [comment]
I parsed the SYNDISP copybook with the new version of python code.
The EBCDIC to ASCII conversion program worked correctly but didn't gave a proper output.

**Comment by anilcert** [comment]
After the fix we are able to convert the copybook to json which has an option to parse the copybook having OCCURS DEPENDING ON.

Thank you
