### ISSUE TITLE
Questions on Packed Decimal Coversion

### ISSUE THREAD

**Issue by granand** [aws-samples/mainframe-data-utilities#8]
Hi Luis,
I looked at your conversion code, thanks for your contribution. Had a quick question on how we convert the packed decimal.
In the code snippet below, why are we checking bytes.hex()[-1:] != "b". please advise.

        return ("" if bytes.hex()[-1:] != "d" and bytes.hex()[-1:] != "b" else "-") + bytes.hex()[:-1]

**Comment by luisdant** [comment]
Hi. It’s checking the negative sign in the last half byte. I’ve never seen a “b” but there are documents/publications saying it’s possible, like this one: https://www.ibm.com/docs/en/cobol-zos/6.1?topic=arithmetic-sign-representation-zoned-packed-decimal-data

**Comment by granand** [comment]
Thanks Luis for the quick turn around!! I have never seen it too. So got curious. Always thought it's "C" for positive and "D" for negative. Glad l learnt something new. Thanks again!!

**Comment by luisdant** [comment]
My pleasure. 

Great to see you reading the core of the code. 

Questions and ideas are very welcome! 

Closing the ticket.

**Comment by granand** [comment]
Thanks Luis!  I went through the link that you shared. Looks like ''b' could represent a negative number for zoned decimal (USAGE DISPLAY). If you look at this  https://www.ibm.com/docs/en/cobol-zos/6.1?topic=data-examples-numeric-internal-representation looks like we could just check C and D and ignore B
<img width="797" alt="image" src="https://user-images.githubusercontent.com/17972094/167212220-1b65f525-baa0-402d-836e-33b290ecef28.png">
